# fly.toml app configuration file generated for ancient-water-2934 on 2023-08-24T10:31:47+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ancient-water-2934"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
